// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvkxpwupjvnxhbvdapis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2a3hwd3VwanZueGhidmRhcGlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwNjIzMjksImV4cCI6MjA4OTYzODMyOX0.u04wm0tFvTleW6L5QUBEqg0sIRp3wBkVB2U8fiSQYNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});